version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@theholocron/babel-preset"
    versions:
    - 0.3.10
    - 0.4.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: simple-git
    versions:
    - 2.31.0
    - 2.32.0
    - 2.34.2
    - 2.35.0
    - 2.35.1
    - 2.35.2
    - 2.36.0
    - 2.36.1
    - 2.36.2
    - 2.37.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@theholocron/eslint-config"
    versions:
    - 0.4.1
  - dependency-name: "@theholocron/browserslist-config"
    versions:
    - 0.1.12
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: "@hidoo/sassdoc-to-markdown"
    versions:
    - 0.4.2
